source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Demos' do
    use_frameworks!

    pod 'AFNetworking', '4.0.1'
    pod 'Masonry','~> 1.1'
    #网易云信IM
    pod 'NIMSDK_LITE', '9.2.5'
    pod 'YYText', '1.0.7'
    
end
